package project

import (
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"os"
	"path"
	"strings"

	"paper-server/internal/auth"
)

const (
	maxUploadRequestSize = 100 << 20 // 100 MiB
	maxUploadFileSize    = 20 << 20  // 20 MiB per file
)

// RegisterUploadRoute registers the project file/folder upload endpoint.
func RegisterUploadRoute(
	mux *http.ServeMux,
	handler *Handler,
	authHandler *auth.Handler,
) {
	mux.Handle(
		"/api/projects/{projectId}/upload",
		authHandler.RequireAuth(http.HandlerFunc(handler.Upload)),
	)
}

// Upload uploads one or more files into a project.
//
// The request must be multipart/form-data.
//
// Form fields:
//
//   - files: one or more files
//   - target: optional project-relative destination folder
//
// For folder uploads, the multipart filename can contain the
// browser-provided relative path.
func (h *Handler) Upload(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(
			w,
			"method not allowed",
			http.StatusMethodNotAllowed,
		)
		return
	}

	projectID := r.PathValue("projectId")

	if projectID == "" {
		writeJSON(w, http.StatusBadRequest, map[string]string{
			"message": "Project ID is required.",
		})
		return
	}

	userID, ok := auth.UserIDFromContext(r.Context())
	if !ok {
		http.Error(
			w,
			"Unauthorized",
			http.StatusUnauthorized,
		)
		return
	}

	// Uploading modifies project contents, so only the owner or
	// EDITOR members should be allowed to do it.
	canEdit, err := h.service.CanEdit(projectID, userID)
	if err != nil {
		handleProjectAccessError(w, err)
		return
	}

	if !canEdit {
		writeJSON(w, http.StatusForbidden, map[string]string{
			"message": "You do not have permission to modify this project.",
		})
		return
	}

	r.Body = http.MaxBytesReader(
		w,
		r.Body,
		maxUploadRequestSize,
	)

	if err := r.ParseMultipartForm(maxUploadRequestSize); err != nil {
		writeJSON(w, http.StatusRequestEntityTooLarge, map[string]string{
			"message": "Upload is too large or invalid multipart data.",
		})
		return
	}

	target := r.FormValue("target")

	if target != "" {
		target, err = normalizeUploadPath(target)
		if err != nil {
			writeJSON(w, http.StatusBadRequest, map[string]string{
				"message": "Invalid upload target.",
			})
			return
		}

		targetPath, err := h.storage.FilePath(
			projectID,
			target,
		)
		if err != nil {
			writeJSON(w, http.StatusBadRequest, map[string]string{
				"message": "Invalid upload target.",
			})
			return
		}

		info, err := os.Stat(targetPath)
		if err != nil {
			if os.IsNotExist(err) {
				writeJSON(w, http.StatusNotFound, map[string]string{
					"message": "Upload target folder not found.",
				})
				return
			}

			writeJSON(w, http.StatusInternalServerError, map[string]string{
				"message": "Failed to inspect upload target.",
			})
			return
		}

		if !info.IsDir() {
			writeJSON(w, http.StatusBadRequest, map[string]string{
				"message": "Upload target is not a folder.",
			})
			return
		}
	}

	files := r.MultipartForm.File["files"]

	if len(files) == 0 {
		writeJSON(w, http.StatusBadRequest, map[string]string{
			"message": "At least one file is required.",
		})
		return
	}

	type uploadItem struct {
		header *multipart.FileHeader
		path   string
	}

	items := make([]uploadItem, 0, len(files))
	seen := make(map[string]struct{}, len(files))

	// Each uploaded file must have a corresponding relative path.
	paths := r.MultipartForm.Value["paths"]

	if len(paths) != len(files) {
		writeJSON(w, http.StatusBadRequest, map[string]string{
			"message": "Each uploaded file must have a corresponding relative path.",
		})
		return
	}

	// Validate everything before writing anything.
	for i, header := range files {
		fmt.Printf(
			"UPLOAD DEBUG: filename=%q path=%q size=%d\n",
			header.Filename,
			paths[i],
			header.Size,
		)

		relativePath, err := normalizeUploadPath(paths[i])
		if err != nil {
			writeJSON(w, http.StatusBadRequest, map[string]string{
				"message": fmt.Sprintf(
					"Invalid file path %q.",
					paths[i],
				),
			})
			return
		}

		if target != "" {
			relativePath = path.Join(
				target,
				relativePath,
			)

			// Normalize again after joining with target.
			relativePath, err = normalizeUploadPath(relativePath)
			if err != nil {
				writeJSON(w, http.StatusBadRequest, map[string]string{
					"message": "Invalid upload path.",
				})
				return
			}
		}

		// current.pdf is generated by the compiler.
		if relativePath == "current.pdf" {
			writeJSON(w, http.StatusBadRequest, map[string]string{
				"message": "current.pdf is reserved for compiled output.",
			})
			return
		}

		if header.Size > maxUploadFileSize {
			writeJSON(w, http.StatusRequestEntityTooLarge, map[string]string{
				"message": fmt.Sprintf(
					"File %q exceeds the 20 MiB limit.",
					header.Filename,
				),
			})
			return
		}

		if _, exists := seen[relativePath]; exists {
			writeJSON(w, http.StatusConflict, map[string]string{
				"message": fmt.Sprintf(
					"File %q was included more than once.",
					relativePath,
				),
			})
			return
		}

		seen[relativePath] = struct{}{}

		fullPath, err := h.storage.FilePath(
			projectID,
			relativePath,
		)
		if err != nil {
			writeJSON(w, http.StatusBadRequest, map[string]string{
				"message": fmt.Sprintf(
					"Invalid file path %q.",
					relativePath,
				),
			})
			return
		}

		if _, err := os.Stat(fullPath); err == nil {
			writeJSON(w, http.StatusConflict, map[string]string{
				"message": fmt.Sprintf(
					"Path already exists: %s",
					relativePath,
				),
			})
			return
		} else if !os.IsNotExist(err) {
			writeJSON(w, http.StatusInternalServerError, map[string]string{
				"message": "Failed to inspect project files.",
			})
			return
		}

		items = append(items, uploadItem{
			header: header,
			path:   relativePath,
		})
	}

	created := make([]string, 0, len(items))

	// Write files.
	for _, item := range items {
		file, err := item.header.Open()
		if err != nil {
			rollbackUploads(
				h.storage,
				projectID,
				created,
			)

			writeJSON(w, http.StatusInternalServerError, map[string]string{
				"message": fmt.Sprintf(
					"Failed to open %q.",
					item.path,
				),
			})
			return
		}

		err = h.storage.createUploadedFile(
			projectID,
			item.path,
			file,
			item.header.Size,
		)

		_ = file.Close()

		if err != nil {
			rollbackUploads(
				h.storage,
				projectID,
				created,
			)

			if errors.Is(err, ErrAlreadyExists) {
				writeJSON(w, http.StatusConflict, map[string]string{
					"message": fmt.Sprintf(
						"Path already exists: %s",
						item.path,
					),
				})
				return
			}

			writeJSON(w, http.StatusInternalServerError, map[string]string{
				"message": fmt.Sprintf(
					"Failed to upload %q.",
					item.path,
				),
			})
			return
		}

		created = append(created, item.path)
	}

	writeJSON(
		w,
		http.StatusCreated,
		UploadResponse{
			Files: created,
		},
	)
}

type UploadResponse struct {
	Files []string `json:"files"`
}

func normalizeUploadPath(value string) (string, error) {
	value = strings.TrimSpace(value)

	if value == "" {
		return "", ErrInvalidPath
	}

	// Don't allow Windows separators to sneak through on a Linux server.
	if strings.Contains(value, "\\") {
		return "", ErrInvalidPath
	}

	cleaned := path.Clean(value)

	if cleaned == "." ||
		cleaned == ".." ||
		strings.HasPrefix(cleaned, "../") ||
		strings.HasPrefix(cleaned, "/") {
		return "", ErrInvalidPath
	}

	return cleaned, nil
}

func (s *Storage) createUploadedFile(
	projectID string,
	filePath string,
	source io.Reader,
	size int64,
) error {
	fullPath, err := s.safeFilePath(
		projectID,
		filePath,
	)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(
		filepathDir(fullPath),
		0755,
	); err != nil {
		return fmt.Errorf(
			"create upload directory: %w",
			err,
		)
	}

	file, err := os.OpenFile(
		fullPath,
		os.O_WRONLY|os.O_CREATE|os.O_EXCL,
		0644,
	)
	if err != nil {
		if os.IsExist(err) {
			return ErrAlreadyExists
		}

		return fmt.Errorf(
			"create uploaded file: %w",
			err,
		)
	}

	written, copyErr := io.Copy(
		file,
		io.LimitReader(
			source,
			maxUploadFileSize+1,
		),
	)

	closeErr := file.Close()

	if copyErr != nil {
		_ = os.Remove(fullPath)
		return fmt.Errorf(
			"write uploaded file: %w",
			copyErr,
		)
	}

	if closeErr != nil {
		_ = os.Remove(fullPath)
		return fmt.Errorf(
			"close uploaded file: %w",
			closeErr,
		)
	}

	if written > maxUploadFileSize ||
		(size >= 0 && written != size) {
		_ = os.Remove(fullPath)
		return errors.New("uploaded file size is invalid")
	}

	return nil
}

func filepathDir(filePath string) string {
	index := strings.LastIndex(
		filePath,
		string(os.PathSeparator),
	)

	if index < 0 {
		return "."
	}

	return filePath[:index]
}

func rollbackUploads(
	storage *Storage,
	projectID string,
	paths []string,
) {
	for _, filePath := range paths {
		_ = storage.DeleteFile(
			projectID,
			filePath,
		)
	}
}
