import type { Metadata } from "next";
import {Inter, Poppins} from "next/font/google";
import "./globals.css";
import {UserProvider} from "@/providers/UserContext";
import {Toaster} from "@/components/ui/toast";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
      <html
          lang="en"
          className={`${inter.variable} ${poppins.variable} h-full antialiased`}
      >
      <body className="min-h-full flex flex-col">
      <UserProvider>
        {children}
        <Toaster/>
      </UserProvider>
      </body>
      </html>
  );
}
